[project]
channels = ["https://conda.modular.com/max-nightly", "https://conda.modular.com/max", "https://repo.prefix.dev/modular-community", "conda-forge"]
name = "mojo-medassist"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
max = "*"
python = ">=3.13.5,<3.14"
numpy = ">=2.3.2,<3"
pandas = ">=2.3.1,<3"
matplotlib = ">=3.10.3,<4"
scikit-learn = ">=1.7.1,<2"
awscli = ">=2.27.60,<3"
kaggle = ">=1.6.17,<2"
datasets = ">=3.6.0,<4"
pytorch-cpu = ">=2.7.1,<3"
transformers = ">=4.53.3,<5"
seaborn = ">=0.13.2,<0.14"
protobuf = ">=5.29.3,<6"
accelerate = ">=1.9.0,<2"
huggingface_hub = ">=0.33.4,<0.34"
bitsandbytes = ">=0.46.1,<0.47"
llama-cpp-python = ">=0.2.24,<0.3"
requests = ">=2.32.4,<3"
